substitutions:
  ha_name: Garage
  ha_id: hagaga1
  dev_name: hagaga1

  dev_platform: ESP32
  dev_board: esp32doit-devkit-v1

  wifi_ssid: !secret wifi_name
  wifi_pw: !secret wifi_password
  wifi_fallback_pw: !secret wifi_fallback_password
  wifi_dom: !secret wifi_domain
  api_pw: !secret api_password
  ota_pw: !secret ota_password
esphome:
  name: ${dev_name}

esp32:
  board: ${dev_board}

# WiFi connection
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pw}
  domain: ${wifi_dom}
  fast_connect: true
  ap:
    ssid: ${dev_name}
    password: ${wifi_fallback_pw}

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: ${api_pw}

# Enable over-the-air updates
ota:
  password: ${ota_pw}

# Enable Web server
web_server:
  port: 80

switch:
  - platform: gpio
    pin: 13
    name: gate switch
    
binary_sensor:
- platform: gpio
  pin: 27
  name: motion
- platform: gpio
  pin: 17
  name: gate operational
  filters:
    invert:

sensor:
  - platform: ultrasonic
    trigger_pin: 33
    echo_pin: 25
    name: Sonar 1
    timeout: 3m
    update_interval: 2s
    pulse_time: 5us
  - platform: ultrasonic
    trigger_pin: 32
    echo_pin: 35
    name: Sonar 2
    timeout: 3m
    update_interval: 2s
    pulse_time: 5us

light:    
  - platform: fastled_clockless
    id: ${ha_id}_neopixel_1
    name: fastled 1
    rgb_order : GRB
    chipset: WS2812
    pin: 19
    num_leds: 30    
  - platform: fastled_clockless
    id: ${ha_id}_neopixel_2
    name: fastled 2
    rgb_order : GRB
    chipset: WS2812
    pin: 21
    num_leds: 30
  