substitutions:
  ha_name: Garage
  ha_id: hagaga1
  dev_name: hagaga1

  dev_platform: ESP32
  dev_board: esp32doit-devkit-v1

  wifi_ssid: !secret wifi_name
  wifi_pw: !secret wifi_password
  wifi_fallback_pw: !secret wifi_fallback_password
  wifi_dom: !secret wifi_domain
  api_pw: !secret api_password
  ota_pw: !secret ota_password
esphome:
  name: ${dev_name}

esp32:
  board: ${dev_board}
  framework:
    type: esp-idf
    version: 5.1.1

# WiFi connection
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pw}
  domain: ${wifi_dom}
  fast_connect: true
  ap:
    ssid: ${dev_name}
    password: ${wifi_fallback_pw}

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: ${api_pw}

# Enable over-the-air updates
ota:
  password: ${ota_pw}

# Enable Web server
web_server:
  port: 80

external_components:
  - source:
      type: local
      path: my_components

ultrasonic_garage:
  name: ${ha_name}
  id: ${ha_id}
  update_interval: 16ms
  gate:
    activate_pin: 13
    trigger_time: 2s
  gate_sensor:
    pin: 17
    inverted: True
  gate_sonar:
    trigger_pin: 33
    echo_pin: 25
  car_sonar:
    trigger_pin: 32
    echo_pin: 35
  motion_sensor:    
    pin: 27
    min_on: 2s
    min_off: 1s
  light_control:
    motion:
    - set_light: 
        id: part1   
        effect: "Scan Fast Reversed"
        blue: 1
        red: 0
        green: 0
    - set_light: 
        id: part2
        effect: "Fill Fast"    
    distance_gate:      
    - set_light: 
        id: part1   
        effect: "Distance Gate"
    distance_car:
    - set_light: 
        id: part2
        effect: "Distance Car"          

light:
- platform: partition
  id: part1
  name: "Partition Light 1"
  segments:
  - id: ${ha_id}_neopixel_1
    from: 0
    to: 39
  effects: addressable_rainbow
- platform: partition
  id: part2
  name: "Partition Light 2"
  segments:
  - id: ${ha_id}_neopixel_1
    from: 40
    to: 79
  effects: addressable_rainbow
- platform: esp32_rmt_led_strip
  id: ${ha_id}_neopixel_1
  internal: True
  rmt_channel: 3
  rgb_order : GRB
  chipset: WS2812
  pin: 21
  num_leds: 300    
- platform: esp32_rmt_led_strip  
  id: ${ha_id}_neopixel_2
  internal: True
  rmt_channel: 4
  rgb_order : GRB
  chipset: WS2812
  pin: 19
  num_leds: 300
